title: "出先で走る"
description: "出先で走る、モチベアップのためのページ"

# Minimal Mistakes を GitHub Pages で使う設定
remote_theme: fongandrew/hydeout


plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

url: "https://shuntarohata.github.io"
baseurl: "/RunningLog" # リポジトリ名
repository: "shuntarohata/RunningLog"

author:
  name: "Shuntaro Hata"

# ナビゲーションメニュー
# Minimal Mistakes では defaults か navigation.yml を使うことが多い
navigation:
  - title: "ホーム"
    url: /
  - title: "記事"
    url: /posts/

# MarkdownでHTMLを許可
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Minimal Mistakes の推奨設定
markdown: kramdown
theme: null   # remote_theme を使うので null にする
